spring.application.name=emailAsAService
spring.config.import=optional:file:.env[.properties]
app.host=${HOST}
app.username=${USERNAME}
app.port=${PORT}
app.emailpassword=${EMAILPASSWORD}
app.password=${PASSWORD}